import { useState } from 'react'
import type { FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { api, send } from '../../api/client'
import { ErrorNotice, Field, Loading } from '../../components/Feedback'
import { StatusBadge } from '../../components/StatusBadge'
import { Button } from '../../components/ui/button'
import { Input } from '../../components/ui/input'
import { FilesPanel } from '../collaboration/FilesPanel'
import { useSession } from '../auth/useSession'
import { hasCapability } from '../auth/types'
import type { BomItem, ComponentOption, Product, ProductRevision, ProductVariant, UnitOfMeasure } from './types'
import { labelForCode } from '../../lib/labels'
import { FirmwarePanel, RoutesPanel, TechnologyPanel } from './ProductDefinitions'

const tabs = ['Огляд', 'Версії', 'Специфікація', 'Технологічна карта', 'Прошивки', 'Виробничий маршрут', 'Документи'] as const
export function ProductDetail() {
  const { id = '' } = useParams(), [tab, setTab] = useState<(typeof tabs)[number]>('Огляд'), [selected, setSelected] = useState(''), [selectedVariant, setSelectedVariant] = useState('')
  const product = useQuery({ queryKey: ['product', id], queryFn: ({ signal }) => api<Product>(`/products/${id}`, { signal }) })
  const variants = useQuery({ queryKey: ['product-variants', id], queryFn: ({ signal }) => api<ProductVariant[]>(`/products/${id}/variants`, { signal }) })
  const revisions = useQuery({ queryKey: ['product-revisions', id], queryFn: ({ signal }) => api<ProductRevision[]>(`/products/${id}/revisions`, { signal }) })
  const { data: user } = useSession()
  const canEdit = hasCapability(user, 'MANAGE_ENGINEERING')
  if (product.isPending || variants.isPending || revisions.isPending) return <Loading />
  if (!product.data) return <ErrorNotice error={product.error || new Error('Виріб не знайдено.')} />
  const variantId = selectedVariant || variants.data?.[0]?.id || ''
  const variant = variants.data?.find(item => item.id === variantId)
  const variantRevisions = revisions.data?.filter(item => item.variant_id === variantId) ?? []
  const revisionId = variantRevisions.some(item => item.id === selected) ? selected : variant?.current_revision_id || variantRevisions[0]?.id || ''
  const revision = variantRevisions.find(item => item.id === revisionId)
  const currentRevision = variantRevisions.find(item => item.id === variant?.current_revision_id)
  return <><Link className="back-link" to="/products">← До продукції</Link><div className="page-heading"><div><p className="eyebrow">{product.data.code} · {product.data.category_name}</p><h1>{product.data.name}</h1><p className="page-description">{product.data.description || 'Опис ще не додано.'}</p></div><StatusBadge value={product.data.lifecycle} /></div><div className="view-controls"><Field label="Комплектація"><select className="form-input" value={variantId} onChange={event => { setSelectedVariant(event.target.value); setSelected('') }}>{variants.data?.map(item => <option key={item.id} value={item.id}>{item.name} · {item.code}</option>)}</select></Field><Field label="Версія"><select className="form-input" value={revisionId} onChange={event => setSelected(event.target.value)}><option value="">Версій немає</option>{variantRevisions.map(item => <option key={item.id} value={item.id}>{item.revision_code} · {labelForCode(item.status)}</option>)}</select></Field></div><div className="tabs">{tabs.map(value => <button key={value} className={tab === value ? 'selected' : ''} onClick={() => setTab(value)}>{value}</button>)}</div>
    {tab === 'Огляд' && <><dl className="detail-grid"><div><dt>Категорія</dt><dd>{product.data.category_name}</dd></div><div><dt>Режим обліку</dt><dd>{labelForCode(product.data.tracking_mode)}</dd></div><div><dt>Комплектація</dt><dd>{variant?.name ?? 'Не створена'}</dd></div><div><dt>Чинна версія</dt><dd>{currentRevision?.revision_code ?? 'Ще не затверджена'}</dd></div><div><dt>Собівартість</dt><dd>{revision?.standard_cost === null ? 'Не розраховано' : revision ? `${revision.standard_cost} ${revision.currency}` : '—'}</dd></div><div><dt>Джерело</dt><dd>{revision?.source_setup_id ? 'Передано зі схваленої розробки' : 'Створено в каталозі'}</dd></div></dl>{revision && <Characteristics revision={revision} canEdit={canEdit} />}<FilesPanel owner={{ kind: 'product', id }} /></>}
    {tab === 'Версії' && <><Variants productId={id} rows={variants.data ?? []} canEdit={canEdit} select={setSelectedVariant} /><Revisions productId={id} variantId={variantId} rows={variantRevisions} selected={revisionId} canEdit={canEdit} select={setSelected} /></>}
    {tab === 'Специфікація' && <Bom revision={revision} canEdit={canEdit} />}{tab === 'Технологічна карта' && <TechnologyPanel revision={revision} canEdit={canEdit} />}
    {tab === 'Прошивки' && <FirmwarePanel revision={revision} canEdit={canEdit} />}{tab === 'Виробничий маршрут' && <RoutesPanel revision={revision} canEdit={canEdit} />}{tab === 'Документи' && revisionId && <FilesPanel owner={{ kind: 'product_revision', id: revisionId }} />}</>
}

function Characteristics({ revision, canEdit }: { revision: ProductRevision; canEdit: boolean }) {
  const cache = useQueryClient(), [json, setJson] = useState(JSON.stringify(revision.technical_characteristics, null, 2)), [cost, setCost] = useState(revision.standard_cost ?? ''), [error, setError] = useState('')
  const mutation = useMutation({ mutationFn: (technical_characteristics: Record<string, unknown>) => send<ProductRevision>(`/products/revisions/${revision.id}`, 'PUT', { revision_code: revision.revision_code, technical_characteristics, standard_cost: cost || null, currency: revision.currency, revision_instructions: revision.revision_instructions }), onSuccess: async () => cache.invalidateQueries({ queryKey: ['product-revisions', revision.product_id] }) })
  function submit(event: FormEvent) { event.preventDefault(); try { const value: unknown = JSON.parse(json); if (!value || Array.isArray(value) || typeof value !== 'object') throw new Error(); setError(''); mutation.mutate(value as Record<string, unknown>) } catch { setError('Характеристики мають бути коректним JSON-об’єктом.') } }
  return <section><div className="section-heading"><h2>Технічні характеристики · {revision.revision_code}</h2><StatusBadge value={revision.status} /></div>{Object.entries(revision.technical_characteristics).length ? <dl className="detail-grid">{Object.entries(revision.technical_characteristics).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl> : <p className="empty-state">Характеристики ще не заповнено.</p>}{canEdit && revision.status === 'DRAFT' && <form className="form-panel form-stack" onSubmit={submit}><Field label="Характеристики (JSON)"><textarea className="form-input" rows={7} value={json} onChange={event => setJson(event.target.value)} /></Field><Field label="Ручна оцінка собівартості"><Input type="number" min="0" step="0.01" placeholder="Не розраховано" value={cost} onChange={event => setCost(event.target.value)} /></Field>{error && <p role="alert">{error}</p>}<ErrorNotice error={mutation.error} /><Button type="submit" disabled={mutation.isPending}>Зберегти характеристики</Button></form>}</section>
}

function Variants({ productId, rows, canEdit, select }: { productId: string; rows: ProductVariant[]; canEdit: boolean; select: (id: string) => void }) {
  const cache = useQueryClient(), [code, setCode] = useState(''), [name, setName] = useState('')
  const create = useMutation({ mutationFn: () => send<ProductVariant>(`/products/${productId}/variants`, 'POST', { code, name, description: '' }), onSuccess: async item => { await Promise.all([cache.invalidateQueries({ queryKey: ['product-variants', productId] }), cache.invalidateQueries({ queryKey: ['product', productId] })]); setCode(''); setName(''); select(item.id) } })
  return <section className="form-panel"><div className="section-heading"><h2>Комплектації</h2><span>{rows.length}</span></div>{canEdit && <form className="filters" onSubmit={event => { event.preventDefault(); create.mutate() }}><Input required placeholder="Код комплектації" value={code} onChange={event => setCode(event.target.value)} /><Input required placeholder="Назва комплектації" value={name} onChange={event => setName(event.target.value)} /><Button type="submit" disabled={create.isPending}>Створити комплектацію</Button></form>}<ErrorNotice error={create.error} /><div className="table-scroll"><table><thead><tr><th>Код</th><th>Назва</th><th>Чинна версія</th></tr></thead><tbody>{rows.map(item => <tr key={item.id}><td>{item.code}</td><td><button className="record-link" onClick={() => select(item.id)}>{item.name}</button></td><td>{item.current_revision_id ? 'Затверджена' : 'Не затверджена'}</td></tr>)}</tbody></table></div></section>
}

function Revisions({ productId, variantId, rows, selected, canEdit, select }: { productId: string; variantId: string; rows: ProductRevision[]; selected: string; canEdit: boolean; select: (id: string) => void }) {
  const cache = useQueryClient(), [code, setCode] = useState(''), [cloneSource, setCloneSource] = useState(''), [cloneCode, setCloneCode] = useState('')
  const refresh = async () => cache.invalidateQueries({ queryKey: ['product-revisions', productId] })
  const create = useMutation({ mutationFn: () => send<ProductRevision>(`/products/${productId}/revisions?variant_id=${variantId}`, 'POST', { revision_code: code, technical_characteristics: {}, standard_cost: null, currency: 'UAH', revision_instructions: '' }), onSuccess: async item => { await refresh(); setCode(''); select(item.id) } })
  const clone = useMutation({ mutationFn: () => send<ProductRevision>(`/products/revisions/${cloneSource}/clone`, 'POST', { revision_code: cloneCode }), onSuccess: async item => { await refresh(); setCloneSource(''); setCloneCode(''); select(item.id) } })
  const transition = useMutation({ mutationFn: ({ id, status }: { id: string; status: string }) => send(`/products/revisions/${id}/status`, 'POST', { status }), onSuccess: refresh })
  return <section className="form-panel"><div className="section-heading"><h2>Версії комплектації</h2><span>{rows.length}</span></div>{canEdit && variantId && <form className="filters" onSubmit={event => { event.preventDefault(); create.mutate() }}><Input placeholder="Код нової версії" required value={code} onChange={event => setCode(event.target.value)} /><Button type="submit">Створити чернетку</Button></form>}{cloneSource && <form className="filters" onSubmit={event => { event.preventDefault(); clone.mutate() }}><Input required autoFocus placeholder="Код нової версії" value={cloneCode} onChange={event => setCloneCode(event.target.value)} /><Button type="submit" disabled={clone.isPending}>Скопіювати</Button><Button type="button" variant="outline" onClick={() => setCloneSource('')}>Скасувати</Button></form>}<ErrorNotice error={create.error || clone.error || transition.error} /><div className="table-scroll"><table><thead><tr><th>Версія</th><th>Стан</th><th>Джерело</th><th>Собівартість</th><th>Дії</th></tr></thead><tbody>{rows.map(item => <tr key={item.id} className={selected === item.id ? 'selected-row' : ''}><td><button className="record-link" onClick={() => select(item.id)}>{item.revision_code}</button></td><td><StatusBadge value={item.status} /></td><td>{item.source_setup_id ? 'Передано з розробки' : 'Вручну'}</td><td>{item.standard_cost === null ? 'Не розраховано' : `${item.standard_cost} ${item.currency}`}</td><td><span className="form-actions">{canEdit && item.status === 'DRAFT' && <Button variant="outline" onClick={() => transition.mutate({ id: item.id, status: 'IN_REVIEW' })}>На перевірку</Button>}{canEdit && item.status === 'IN_REVIEW' && <Button onClick={() => transition.mutate({ id: item.id, status: 'RELEASED' })}>Затвердити</Button>}{canEdit && <Button variant="outline" onClick={() => { setCloneSource(item.id); setCloneCode('') }}>Скопіювати в нову версію</Button>}</span></td></tr>)}{!rows.length && <tr><td colSpan={5}>Версій ще немає.</td></tr>}</tbody></table></div></section>
}

function Bom({ revision, canEdit }: { revision: ProductRevision | undefined; canEdit: boolean }) {
  const revisionId = revision?.id ?? '', cache = useQueryClient()
  const [componentId, setComponentId] = useState(''), [quantity, setQuantity] = useState('1')
  const [uomId, setUomId] = useState(''), [position, setPosition] = useState(''), [required, setRequired] = useState(true)
  const query = useQuery({ queryKey: ['bom', revisionId], enabled: !!revisionId, queryFn: ({ signal }) => api<BomItem[]>(`/products/revisions/${revisionId}/bom`, { signal }) })
  const components = useQuery({ queryKey: ['component-options'], queryFn: ({ signal }) => api<ComponentOption[]>('/components/options', { signal }) })
  const uoms = useQuery({ queryKey: ['uoms'], queryFn: ({ signal }) => api<UnitOfMeasure[]>('/components/uoms', { signal }) })
  const add = useMutation({ mutationFn: () => send<BomItem>(`/products/revisions/${revisionId}/bom`, 'POST', { component_id: componentId, quantity, uom_id: uomId || null, position, sequence: query.data?.length ?? 0, required, notes: '' }), onSuccess: async () => { setComponentId(''); setQuantity('1'); setUomId(''); setPosition(''); await cache.invalidateQueries({ queryKey: ['bom', revisionId] }) } })
  const remove = useMutation({ mutationFn: (itemId: string) => send<void>(`/products/revisions/${revisionId}/bom/${itemId}`, 'DELETE'), onSuccess: async () => cache.invalidateQueries({ queryKey: ['bom', revisionId] }) })
  if (!revision) return <p className="empty-state">Оберіть версію.</p>
  const editable = canEdit && revision.status === 'DRAFT'
  return <section className="form-panel"><div className="section-heading"><div><h2>Специфікація версії {revision.revision_code}</h2><p className="page-description">Склад комплектуючих фіксується після затвердження версії.</p></div><StatusBadge value={revision.status} /></div>
    {editable && <form className="bom-editor" onSubmit={event => { event.preventDefault(); add.mutate() }}><Field label="Комплектуюча"><select required className="form-input" value={componentId} onChange={event => setComponentId(event.target.value)}><option value="">Оберіть компонент</option>{components.data?.map(item => <option key={item.id} value={item.id}>{item.name}{item.sku ? ` · ${item.sku}` : ''}</option>)}</select></Field><Field label="Кількість"><Input required type="number" min="0.0001" step="0.0001" value={quantity} onChange={event => setQuantity(event.target.value)} /></Field><Field label="Одиниця"><select className="form-input" value={uomId} onChange={event => setUomId(event.target.value)}><option value="">За замовчуванням компонента</option>{uoms.data?.map(item => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></Field><Field label="Позиція"><Input placeholder="Напр. M1, FC, корпус" value={position} onChange={event => setPosition(event.target.value)} /></Field><label className="bom-required"><input type="checkbox" checked={required} onChange={event => setRequired(event.target.checked)} /> Обов’язкова позиція</label><Button type="submit" disabled={add.isPending || !componentId}>Додати до специфікації</Button></form>}
    {!editable && <p className="immutable-notice">{revision.status === 'DRAFT' ? 'У вас немає прав редагувати специфікацію.' : 'Ця версія незмінна. Для змін створіть нову чернетку версії.'}</p>}
    <ErrorNotice error={query.error || components.error || uoms.error || add.error || remove.error} />{query.isPending ? <Loading /> : <div className="table-scroll"><table><thead><tr><th>Компонент</th><th>Кількість</th><th>Од.</th><th>Позиція</th><th>Обов’язковий</th>{editable && <th>Дії</th>}</tr></thead><tbody>{query.data?.map(item => <BomRow key={item.id} item={item} revisionId={revisionId} editable={editable} componentName={components.data?.find(component => component.id === item.component_id)?.name ?? 'Компонент недоступний'} uomCode={uoms.data?.find(uom => uom.id === item.uom_id)?.code ?? '—'} onRemove={() => { if (window.confirm('Видалити цю комплектуючу зі специфікації?')) remove.mutate(item.id) }} />)}{!query.data?.length && <tr><td colSpan={editable ? 6 : 5}>Специфікація цієї версії порожня.</td></tr>}</tbody></table></div>}</section>
}

function BomRow({ item, revisionId, editable, componentName, uomCode, onRemove }: { item: BomItem; revisionId: string; editable: boolean; componentName: string; uomCode: string; onRemove: () => void }) {
  const cache = useQueryClient(), [editing, setEditing] = useState(false), [quantity, setQuantity] = useState(item.quantity), [position, setPosition] = useState(item.position), [required, setRequired] = useState(item.required)
  const update = useMutation({ mutationFn: () => send<BomItem>(`/products/revisions/${revisionId}/bom/${item.id}`, 'PUT', { component_id: item.component_id, quantity, uom_id: item.uom_id, position, sequence: item.sequence, required, notes: item.notes }), onSuccess: async () => { setEditing(false); await cache.invalidateQueries({ queryKey: ['bom', revisionId] }) } })
  if (editing) return <tr><td>{componentName}</td><td><Input aria-label="Кількість комплектуючої" type="number" min="0.0001" step="0.0001" value={quantity} onChange={event => setQuantity(event.target.value)} /></td><td>{uomCode}</td><td><Input aria-label="Позиція комплектуючої" value={position} onChange={event => setPosition(event.target.value)} /></td><td><input type="checkbox" checked={required} onChange={event => setRequired(event.target.checked)} /></td><td><span className="form-actions"><Button disabled={update.isPending} onClick={() => update.mutate()}>Зберегти</Button><Button variant="outline" onClick={() => setEditing(false)}>Скасувати</Button></span><ErrorNotice error={update.error} /></td></tr>
  return <tr><td>{componentName}</td><td>{item.quantity}</td><td>{uomCode}</td><td>{item.position || '—'}</td><td><input type="checkbox" checked={item.required} readOnly /></td>{editable && <td><span className="form-actions"><Button variant="outline" onClick={() => setEditing(true)}>Змінити</Button><Button variant="destructive" onClick={onRemove}>Видалити</Button></span></td>}</tr>
}
