export type TrackingMode = 'SERIAL' | 'BATCH' | 'QUANTITY'
export interface ProductCategory { id: string; code: string; name: string; description: string; is_active: boolean }
export interface Product { id: string; code: string; name: string; category_id: string; category_name: string; description: string; lifecycle: 'DEVELOPMENT' | 'PRODUCTION' | 'DEPRECATED'; tracking_mode: TrackingMode; current_revision_id: string | null; general_image_attachment_id: string | null; variant_count: number; created_at: string; updated_at: string }
export interface ProductVariant { id: string; product_id: string; code: string; name: string; description: string; is_active: boolean; current_revision_id: string | null; created_at: string; updated_at: string }
export interface ProductRevision { id: string; product_id: string; product_name: string; variant_id: string; variant_name: string; revision_code: string; status: 'DRAFT' | 'IN_REVIEW' | 'RELEASED' | 'RETIRED'; technical_characteristics: Record<string, unknown>; standard_cost: string | null; currency: string; revision_instructions: string; source_setup_id: string | null; source_branch_id: string | null; source_project_id: string | null; released_at: string | null; created_at: string; updated_at: string }
export interface BomItem { id: string; component_id: string; quantity: string; uom_id: string; position: string; sequence: number; required: boolean; notes: string }
export interface ComponentOption { id: string; name: string; sku: string | null }
export interface UnitOfMeasure { id: string; code: string; name: string; precision: number }
export type ContentBlockType = 'TEXT' | 'IMAGE' | 'CHECKLIST' | 'WARNING' | 'FILE' | 'ANNOTATED_IMAGE' | 'MEASUREMENT' | 'VIDEO'
export interface TechnologyBlock { id: string; operation_id: string; block_type: ContentBlockType; sequence: number; payload: Record<string, unknown>; attachment_id: string | null; annotation_source: Record<string, unknown>; annotation_version: number }
export interface ChecklistItem { id: string; block_id: string; text: string; sequence: number; required: boolean; note_required: boolean; photo_required: boolean }
export interface TechnologyOperation { id: string; card_id: string; name: string; sequence: number; expected_result: string; acceptance_criteria: string; blocks: TechnologyBlock[]; checklist_items: ChecklistItem[] }
export interface WorkerPreview { card: { id: string; revision_id: string; title: string; description: string }; operations: TechnologyOperation[] }
export interface FirmwareArtifact { id: string; name: string; description: string }
export interface FirmwareRelease { id: string; artifact_id: string; version: string; firmware_type: string; upstream_version: string; description: string; config_text: string; checksum: string; binary_attachment_id: string | null; config_attachment_id: string | null }
export interface FirmwareRequirement { id: string; revision_id: string; release_id: string; purpose: string; notes: string; configuration: Record<string, unknown>; artifact_id: string; artifact_name: string; artifact_description: string; release_version: string; firmware_type: string; upstream_version: string; release_description: string; config_text: string; checksum: string; binary_attachment_id: string | null; config_attachment_id: string | null }
export interface RouteRole { id: string; code: string; name: string }
export interface ProductionRoute { id: string; revision_id: string; version: number; name: string; description: string }
export interface RouteStage { id: string; route_id: string; code: string; name: string; sequence: number; technology_operation_id: string | null; supports_pass_fail: boolean; measurement_required: boolean; attachment_required: boolean; instructions: string; roles: RouteRole[]; predecessor_ids: string[] }
