"""phase 3 products

Revision: 0009_phase3_products
Revises: 0008_rnd_evolution
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0009_phase3_products"
down_revision: str | Sequence[str] | None = "0008_rnd_evolution"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "firmware_artifacts",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(name)) > 0", name=op.f("ck_firmware_artifacts_name_nonempty")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_firmware_artifacts")),
        sa.UniqueConstraint("name", name="uq_firmware_artifacts_name"),
    )
    op.create_table(
        "product_categories",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(code)) > 0", name=op.f("ck_product_categories_code_nonempty")
        ),
        sa.CheckConstraint(
            "length(trim(name)) > 0", name=op.f("ck_product_categories_name_nonempty")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_categories")),
        sa.UniqueConstraint("code", name="uq_product_categories_code"),
    )
    op.create_table(
        "units_of_measure",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("precision", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(code)) > 0", name=op.f("ck_units_of_measure_code_nonempty")
        ),
        sa.CheckConstraint(
            "length(trim(name)) > 0", name=op.f("ck_units_of_measure_name_nonempty")
        ),
        sa.CheckConstraint(
            "precision BETWEEN 0 AND 6", name=op.f("ck_units_of_measure_precision_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units_of_measure")),
        sa.UniqueConstraint("code", name="uq_units_of_measure_code"),
    )
    op.bulk_insert(
        sa.table(
            "units_of_measure",
            sa.column("id", sa.Uuid()),
            sa.column("code", sa.String()),
            sa.column("name", sa.String()),
            sa.column("precision", sa.Integer()),
        ),
        [
            {
                "id": "10000000-0000-0000-0000-000000000001",
                "code": "PCS",
                "name": "Штука",
                "precision": 0,
            },
            {
                "id": "10000000-0000-0000-0000-000000000002",
                "code": "KG",
                "name": "Кілограм",
                "precision": 3,
            },
            {
                "id": "10000000-0000-0000-0000-000000000003",
                "code": "M",
                "name": "Метр",
                "precision": 3,
            },
            {
                "id": "10000000-0000-0000-0000-000000000004",
                "code": "L",
                "name": "Літр",
                "precision": 3,
            },
        ],
    )
    op.bulk_insert(
        sa.table(
            "product_categories",
            sa.column("id", sa.Uuid()),
            sa.column("code", sa.String()),
            sa.column("name", sa.String()),
            sa.column("description", sa.Text()),
            sa.column("is_active", sa.Boolean()),
        ),
        [
            {
                "id": "20000000-0000-0000-0000-000000000001",
                "code": "UAV",
                "name": "БПЛА",
                "description": "Повітряні платформи",
                "is_active": True,
            },
            {
                "id": "20000000-0000-0000-0000-000000000002",
                "code": "GROUND_STATION",
                "name": "Наземна станція",
                "description": "Наземні комплекси керування",
                "is_active": True,
            },
            {
                "id": "20000000-0000-0000-0000-000000000003",
                "code": "ANTENNA",
                "name": "Антена",
                "description": "Антенні системи",
                "is_active": True,
            },
            {
                "id": "20000000-0000-0000-0000-000000000004",
                "code": "OTHER",
                "name": "Інше",
                "description": "Інші типи продуктів",
                "is_active": True,
            },
        ],
    )
    op.create_table(
        "firmware_releases",
        sa.Column("artifact_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(length=255), nullable=False),
        sa.Column("firmware_type", sa.String(length=255), server_default="", nullable=False),
        sa.Column("upstream_version", sa.String(length=255), server_default="", nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("config_text", sa.Text(), server_default="", nullable=False),
        sa.Column("checksum", sa.String(length=128), server_default="", nullable=False),
        sa.Column("binary_attachment_id", sa.Uuid(), nullable=True),
        sa.Column("config_attachment_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "length(trim(version)) > 0", name=op.f("ck_firmware_releases_version_nonempty")
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["firmware_artifacts.id"],
            name=op.f("fk_firmware_releases_artifact_id_firmware_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["binary_attachment_id"],
            ["attachments.id"],
            name="fk_firmware_releases_binary_attachment_id_attachments",
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["config_attachment_id"],
            ["attachments.id"],
            name="fk_firmware_releases_config_attachment_id_attachments",
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_firmware_releases_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_firmware_releases")),
        sa.UniqueConstraint("artifact_id", "version", name="uq_firmware_releases_artifact_version"),
    )
    op.create_index(
        op.f("ix_firmware_releases_artifact_id"), "firmware_releases", ["artifact_id"], unique=False
    )
    op.create_index(
        op.f("ix_firmware_releases_created_by_id"),
        "firmware_releases",
        ["created_by_id"],
        unique=False,
    )
    op.create_table(
        "products",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("lifecycle", sa.String(length=20), server_default="DEVELOPMENT", nullable=False),
        sa.Column("tracking_mode", sa.String(length=20), nullable=False),
        sa.Column("current_revision_id", sa.Uuid(), nullable=True),
        sa.Column("general_image_attachment_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lifecycle IN ('DEVELOPMENT','PRODUCTION','DEPRECATED')",
            name=op.f("ck_products_lifecycle"),
        ),
        sa.CheckConstraint(
            "tracking_mode IN ('SERIAL','BATCH','QUANTITY')", name=op.f("ck_products_tracking_mode")
        ),
        sa.CheckConstraint("length(trim(code)) > 0", name=op.f("ck_products_code_nonempty")),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_products_name_nonempty")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["product_categories.id"],
            name=op.f("fk_products_category_id_product_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["current_revision_id"],
            ["product_revisions.id"],
            name="fk_products_current_revision_id_product_revisions",
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["general_image_attachment_id"],
            ["attachments.id"],
            name="fk_products_general_image_attachment_id_attachments",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("code", name="uq_products_code"),
    )
    op.create_index(op.f("ix_products_category_id"), "products", ["category_id"], unique=False)
    op.create_index(
        op.f("ix_products_current_revision_id"), "products", ["current_revision_id"], unique=False
    )
    op.create_table(
        "product_revisions",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("revision_code", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="DRAFT", nullable=False),
        sa.Column("source_project_id", sa.Uuid(), nullable=True),
        sa.Column("source_branch_id", sa.Uuid(), nullable=True),
        sa.Column("source_setup_id", sa.Uuid(), nullable=True),
        sa.Column("source_promotion_request_id", sa.Uuid(), nullable=True),
        sa.Column(
            "technical_characteristics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("standard_cost", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="UAH", nullable=False),
        sa.Column("revision_instructions", sa.Text(), server_default="", nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("released_by_id", sa.Uuid(), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status IN ('RELEASED','RETIRED')) = (released_at IS NOT NULL)",
            name=op.f("ck_product_revisions_release_state"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(technical_characteristics) = 'object'",
            name=op.f("ck_product_revisions_technical_object"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','IN_REVIEW','RELEASED','RETIRED')",
            name=op.f("ck_product_revisions_status"),
        ),
        sa.CheckConstraint(
            "length(trim(revision_code)) > 0",
            name=op.f("ck_product_revisions_revision_code_nonempty"),
        ),
        sa.CheckConstraint(
            "standard_cost IS NULL OR standard_cost >= 0",
            name=op.f("ck_product_revisions_cost_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_product_revisions_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_revisions_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["released_by_id"],
            ["users.id"],
            name=op.f("fk_product_revisions_released_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_branch_id"],
            ["rd_branches.id"],
            name=op.f("fk_product_revisions_source_branch_id_rd_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_project_id"],
            ["projects.id"],
            name=op.f("fk_product_revisions_source_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_promotion_request_id"],
            ["rnd_promotion_requests.id"],
            name=op.f("fk_product_revisions_source_promotion_request_id_rnd_promotion_requests"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_setup_id"],
            ["setups.id"],
            name=op.f("fk_product_revisions_source_setup_id_setups"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_revisions")),
        sa.UniqueConstraint("product_id", "id", name="uq_product_revisions_product_id_pair"),
        sa.UniqueConstraint(
            "product_id", "revision_code", name="uq_product_revisions_product_code"
        ),
        sa.UniqueConstraint("source_promotion_request_id", name="uq_product_revisions_promotion"),
    )
    op.create_index(
        op.f("ix_product_revisions_source_branch_id"),
        "product_revisions",
        ["source_branch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_revisions_source_project_id"),
        "product_revisions",
        ["source_project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_revisions_source_setup_id"),
        "product_revisions",
        ["source_setup_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_revisions_status"), "product_revisions", ["status"], unique=False
    )
    op.create_table(
        "firmware_requirements",
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "configuration",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(configuration) = 'object'",
            name=op.f("ck_firmware_requirements_configuration_object"),
        ),
        sa.CheckConstraint(
            "length(trim(purpose)) > 0", name=op.f("ck_firmware_requirements_purpose_nonempty")
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["firmware_releases.id"],
            name=op.f("fk_firmware_requirements_release_id_firmware_releases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["product_revisions.id"],
            name=op.f("fk_firmware_requirements_revision_id_product_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_firmware_requirements")),
        sa.UniqueConstraint(
            "revision_id", "release_id", "purpose", name="uq_firmware_requirements"
        ),
    )
    op.create_index(
        op.f("ix_firmware_requirements_release_id"),
        "firmware_requirements",
        ["release_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_firmware_requirements_revision_id"),
        "firmware_requirements",
        ["revision_id"],
        unique=False,
    )
    op.create_table(
        "product_revision_bom_items",
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("uom_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.String(length=100), server_default="", nullable=False),
        sa.Column("sequence", sa.Integer(), server_default="0", nullable=False),
        sa.Column("required", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_product_revision_bom_items_quantity_positive")
        ),
        sa.CheckConstraint(
            "sequence >= 0", name=op.f("ck_product_revision_bom_items_sequence_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.id"],
            name=op.f("fk_product_revision_bom_items_component_id_components"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["product_revisions.id"],
            name=op.f("fk_product_revision_bom_items_revision_id_product_revisions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uom_id"],
            ["units_of_measure.id"],
            name=op.f("fk_product_revision_bom_items_uom_id_units_of_measure"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_revision_bom_items")),
        sa.UniqueConstraint(
            "revision_id", "component_id", "position", name="uq_revision_bom_component_position"
        ),
    )
    op.create_index(
        op.f("ix_product_revision_bom_items_component_id"),
        "product_revision_bom_items",
        ["component_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_revision_bom_items_revision_id"),
        "product_revision_bom_items",
        ["revision_id"],
        unique=False,
    )
    op.create_table(
        "production_routes",
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["product_revisions.id"],
            name=op.f("fk_production_routes_revision_id_product_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_routes")),
        sa.UniqueConstraint("revision_id", "version", name="uq_routes_revision_version"),
    )
    op.create_index(
        op.f("ix_production_routes_revision_id"), "production_routes", ["revision_id"], unique=False
    )
    op.create_table(
        "technology_cards",
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["product_revisions.id"],
            name=op.f("fk_technology_cards_revision_id_product_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technology_cards")),
        sa.UniqueConstraint("revision_id", name="uq_technology_cards_revision"),
    )
    op.create_index(
        op.f("ix_technology_cards_revision_id"), "technology_cards", ["revision_id"], unique=False
    )
    op.create_table(
        "bom_approved_alternatives",
        sa.Column("bom_item_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=False),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bom_item_id"],
            ["product_revision_bom_items.id"],
            name=op.f("fk_bom_approved_alternatives_bom_item_id_product_revision_bom_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.id"],
            name=op.f("fk_bom_approved_alternatives_component_id_components"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bom_approved_alternatives")),
        sa.UniqueConstraint(
            "bom_item_id", "component_id", name="uq_bom_alternatives_item_component"
        ),
    )
    op.create_table(
        "product_revision_documents",
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("attachment_id", sa.Uuid(), nullable=False),
        sa.Column("document_type", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("sequence", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "document_type IN ('USER_MANUAL','MANUFACTURING','CONFIGURATION',"
            "'DRAWING','WIRING_DIAGRAM','OTHER')",
            name=op.f("ck_product_revision_documents_document_type"),
        ),
        sa.ForeignKeyConstraint(
            ["attachment_id"],
            ["attachments.id"],
            name=op.f("fk_product_revision_documents_attachment_id_attachments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["product_revisions.id"],
            name=op.f("fk_product_revision_documents_revision_id_product_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_revision_documents")),
        sa.UniqueConstraint(
            "attachment_id", name=op.f("uq_product_revision_documents_attachment_id")
        ),
        sa.UniqueConstraint(
            "revision_id", "attachment_id", name="uq_revision_documents_attachment"
        ),
    )
    op.create_index(
        op.f("ix_product_revision_documents_revision_id"),
        "product_revision_documents",
        ["revision_id"],
        unique=False,
    )
    op.create_table(
        "technology_operations",
        sa.Column("card_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("expected_result", sa.Text(), server_default="", nullable=False),
        sa.Column("acceptance_criteria", sa.Text(), server_default="", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(name)) > 0", name=op.f("ck_technology_operations_name_nonempty")
        ),
        sa.CheckConstraint(
            "sequence >= 0", name=op.f("ck_technology_operations_sequence_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["technology_cards.id"],
            name=op.f("fk_technology_operations_card_id_technology_cards"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technology_operations")),
        sa.UniqueConstraint("card_id", "sequence", name="uq_technology_operations_sequence"),
    )
    op.create_index(
        op.f("ix_technology_operations_card_id"), "technology_operations", ["card_id"], unique=False
    )
    op.create_table(
        "route_stages",
        sa.Column("route_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("technology_operation_id", sa.Uuid(), nullable=True),
        sa.Column("supports_pass_fail", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("measurement_required", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("attachment_required", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("instructions", sa.Text(), server_default="", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(trim(code)) > 0", name=op.f("ck_route_stages_code_nonempty")),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_route_stages_name_nonempty")),
        sa.CheckConstraint("sequence >= 0", name=op.f("ck_route_stages_sequence_nonnegative")),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["production_routes.id"],
            name=op.f("fk_route_stages_route_id_production_routes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["technology_operation_id"],
            ["technology_operations.id"],
            name=op.f("fk_route_stages_technology_operation_id_technology_operations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_stages")),
        sa.UniqueConstraint("route_id", "code", name="uq_route_stages_code"),
        sa.UniqueConstraint("route_id", "sequence", name="uq_route_stages_sequence"),
    )
    op.create_index(op.f("ix_route_stages_route_id"), "route_stages", ["route_id"], unique=False)
    op.create_table(
        "technology_content_blocks",
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("block_type", sa.String(length=30), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("attachment_id", sa.Uuid(), nullable=True),
        sa.Column(
            "annotation_source",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("annotation_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "block_type IN ('TEXT','IMAGE','CHECKLIST','WARNING','FILE',"
            "'ANNOTATED_IMAGE','MEASUREMENT','VIDEO')",
            name=op.f("ck_technology_content_blocks_block_type"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(annotation_source) = 'object'",
            name=op.f("ck_technology_content_blocks_annotation_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(payload) = 'object'",
            name=op.f("ck_technology_content_blocks_payload_object"),
        ),
        sa.CheckConstraint(
            "sequence >= 0", name=op.f("ck_technology_content_blocks_sequence_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["attachment_id"],
            ["attachments.id"],
            name=op.f("fk_technology_content_blocks_attachment_id_attachments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["technology_operations.id"],
            name=op.f("fk_technology_content_blocks_operation_id_technology_operations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technology_content_blocks")),
        sa.UniqueConstraint("operation_id", "sequence", name="uq_technology_blocks_sequence"),
    )
    op.create_index(
        op.f("ix_technology_content_blocks_operation_id"),
        "technology_content_blocks",
        ["operation_id"],
        unique=False,
    )
    op.create_table(
        "checklist_template_items",
        sa.Column("block_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("required", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("note_required", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("photo_required", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(text)) > 0", name=op.f("ck_checklist_template_items_text_nonempty")
        ),
        sa.CheckConstraint(
            "sequence >= 0", name=op.f("ck_checklist_template_items_sequence_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["technology_content_blocks.id"],
            name=op.f("fk_checklist_template_items_block_id_technology_content_blocks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checklist_template_items")),
        sa.UniqueConstraint("block_id", "sequence", name="uq_checklist_items_sequence"),
    )
    op.create_index(
        op.f("ix_checklist_template_items_block_id"),
        "checklist_template_items",
        ["block_id"],
        unique=False,
    )
    op.create_table(
        "route_stage_dependencies",
        sa.Column("stage_id", sa.Uuid(), nullable=False),
        sa.Column("predecessor_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "stage_id <> predecessor_id", name=op.f("ck_route_stage_dependencies_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["predecessor_id"],
            ["route_stages.id"],
            name=op.f("fk_route_stage_dependencies_predecessor_id_route_stages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["route_stages.id"],
            name=op.f("fk_route_stage_dependencies_stage_id_route_stages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_stage_dependencies")),
        sa.UniqueConstraint("stage_id", "predecessor_id", name="uq_stage_dependencies_edge"),
    )
    op.create_index(
        op.f("ix_route_stage_dependencies_predecessor_id"),
        "route_stage_dependencies",
        ["predecessor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_route_stage_dependencies_stage_id"),
        "route_stage_dependencies",
        ["stage_id"],
        unique=False,
    )
    op.create_table(
        "route_stage_roles",
        sa.Column("stage_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_route_stage_roles_role_id_roles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["route_stages.id"],
            name=op.f("fk_route_stage_roles_stage_id_route_stages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_stage_roles")),
        sa.UniqueConstraint("stage_id", "role_id", name="uq_route_stage_roles"),
    )
    op.create_index(
        op.f("ix_route_stage_roles_stage_id"), "route_stage_roles", ["stage_id"], unique=False
    )
    op.add_column("attachments", sa.Column("product_id", sa.Uuid(), nullable=True))
    op.add_column("attachments", sa.Column("product_revision_id", sa.Uuid(), nullable=True))
    op.add_column("attachments", sa.Column("firmware_release_id", sa.Uuid(), nullable=True))
    op.drop_constraint(op.f("ck_attachments_one_owner"), "attachments", type_="check")
    op.create_check_constraint(
        op.f("ck_attachments_one_owner"),
        "attachments",
        "num_nonnulls(project_id, task_id, setup_id, component_id, test_id, "
        "firmware_revision_id, branch_id, product_id, product_revision_id, "
        "firmware_release_id) = 1",
    )
    op.create_index(
        op.f("ix_attachments_firmware_release_id"),
        "attachments",
        ["firmware_release_id"],
        unique=False,
    )
    op.create_index(op.f("ix_attachments_product_id"), "attachments", ["product_id"], unique=False)
    op.create_index(
        op.f("ix_attachments_product_revision_id"),
        "attachments",
        ["product_revision_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_attachments_product_revision_id_product_revisions"),
        "attachments",
        "product_revisions",
        ["product_revision_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_attachments_product_id_products"),
        "attachments",
        "products",
        ["product_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_attachments_firmware_release_id_firmware_releases"),
        "attachments",
        "firmware_releases",
        ["firmware_release_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_firmware_releases_binary_attachment_id_attachments",
        "firmware_releases",
        "attachments",
        ["binary_attachment_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_firmware_releases_config_attachment_id_attachments",
        "firmware_releases",
        "attachments",
        ["config_attachment_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_products_general_image_attachment_id_attachments",
        "products",
        "attachments",
        ["general_image_attachment_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_products_current_revision_id_product_revisions",
        "products",
        "product_revisions",
        ["current_revision_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column("components", sa.Column("sku", sa.String(length=100), nullable=True))
    op.add_column(
        "components",
        sa.Column("lifecycle", sa.String(length=20), server_default="ACTIVE", nullable=False),
    )
    op.add_column("components", sa.Column("default_uom_id", sa.Uuid(), nullable=True))
    op.execute(
        "UPDATE components SET default_uom_id = '10000000-0000-0000-0000-000000000001'::uuid"
    )
    op.alter_column("components", "default_uom_id", nullable=False)
    op.create_index(
        op.f("ix_components_default_uom_id"), "components", ["default_uom_id"], unique=False
    )
    op.create_unique_constraint(op.f("uq_components_sku"), "components", ["sku"])
    op.create_foreign_key(
        op.f("fk_components_default_uom_id_units_of_measure"),
        "components",
        "units_of_measure",
        ["default_uom_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_products_current_revision_id_product_revisions", "products", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_products_general_image_attachment_id_attachments", "products", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_firmware_releases_config_attachment_id_attachments",
        "firmware_releases",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_firmware_releases_binary_attachment_id_attachments",
        "firmware_releases",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_components_default_uom_id_units_of_measure"), "components", type_="foreignkey"
    )
    op.drop_constraint(op.f("uq_components_sku"), "components", type_="unique")
    op.drop_index(op.f("ix_components_default_uom_id"), table_name="components")
    op.drop_column("components", "default_uom_id")
    op.drop_column("components", "lifecycle")
    op.drop_column("components", "sku")
    op.drop_constraint(
        op.f("fk_attachments_firmware_release_id_firmware_releases"),
        "attachments",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_attachments_product_id_products"), "attachments", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_attachments_product_revision_id_product_revisions"),
        "attachments",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_attachments_product_revision_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_product_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_firmware_release_id"), table_name="attachments")
    op.drop_constraint(op.f("ck_attachments_one_owner"), "attachments", type_="check")
    op.create_check_constraint(
        op.f("ck_attachments_one_owner"),
        "attachments",
        "num_nonnulls(project_id, task_id, setup_id, component_id, test_id, "
        "firmware_revision_id, branch_id) = 1",
    )
    op.drop_column("attachments", "firmware_release_id")
    op.drop_column("attachments", "product_revision_id")
    op.drop_column("attachments", "product_id")
    op.drop_index(op.f("ix_route_stage_roles_stage_id"), table_name="route_stage_roles")
    op.drop_table("route_stage_roles")
    op.drop_index(
        op.f("ix_route_stage_dependencies_stage_id"), table_name="route_stage_dependencies"
    )
    op.drop_index(
        op.f("ix_route_stage_dependencies_predecessor_id"), table_name="route_stage_dependencies"
    )
    op.drop_table("route_stage_dependencies")
    op.drop_index(
        op.f("ix_checklist_template_items_block_id"), table_name="checklist_template_items"
    )
    op.drop_table("checklist_template_items")
    op.drop_index(
        op.f("ix_technology_content_blocks_operation_id"), table_name="technology_content_blocks"
    )
    op.drop_table("technology_content_blocks")
    op.drop_index(op.f("ix_route_stages_route_id"), table_name="route_stages")
    op.drop_table("route_stages")
    op.drop_index(op.f("ix_technology_operations_card_id"), table_name="technology_operations")
    op.drop_table("technology_operations")
    op.drop_index(
        op.f("ix_product_revision_documents_revision_id"), table_name="product_revision_documents"
    )
    op.drop_table("product_revision_documents")
    op.drop_table("bom_approved_alternatives")
    op.drop_index(op.f("ix_technology_cards_revision_id"), table_name="technology_cards")
    op.drop_table("technology_cards")
    op.drop_index(op.f("ix_production_routes_revision_id"), table_name="production_routes")
    op.drop_table("production_routes")
    op.drop_index(
        op.f("ix_product_revision_bom_items_revision_id"), table_name="product_revision_bom_items"
    )
    op.drop_index(
        op.f("ix_product_revision_bom_items_component_id"), table_name="product_revision_bom_items"
    )
    op.drop_table("product_revision_bom_items")
    op.drop_index(op.f("ix_firmware_requirements_revision_id"), table_name="firmware_requirements")
    op.drop_index(op.f("ix_firmware_requirements_release_id"), table_name="firmware_requirements")
    op.drop_table("firmware_requirements")
    op.drop_index(op.f("ix_product_revisions_status"), table_name="product_revisions")
    op.drop_index(op.f("ix_product_revisions_source_setup_id"), table_name="product_revisions")
    op.drop_index(op.f("ix_product_revisions_source_project_id"), table_name="product_revisions")
    op.drop_index(op.f("ix_product_revisions_source_branch_id"), table_name="product_revisions")
    op.drop_table("product_revisions")
    op.drop_index(op.f("ix_products_current_revision_id"), table_name="products")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_firmware_releases_created_by_id"), table_name="firmware_releases")
    op.drop_index(op.f("ix_firmware_releases_artifact_id"), table_name="firmware_releases")
    op.drop_table("firmware_releases")
    op.drop_table("units_of_measure")
    op.drop_table("product_categories")
    op.drop_table("firmware_artifacts")
    # ### end Alembic commands ###
