"""phase4 orders procurement

Revision: 0010_phase4_orders
Revises: 0009_phase3_products
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0010_phase4_orders"
down_revision: str | Sequence[str] | None = "0009_phase3_products"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("contact_details", sa.Text(), server_default="", nullable=False),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_customers_name_nonempty")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("name", name="uq_customers_name"),
    )
    op.create_table(
        "suppliers",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("contact_details", sa.Text(), server_default="", nullable=False),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_suppliers_name_nonempty")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
        sa.UniqueConstraint("name", name="uq_suppliers_name"),
    )
    op.create_table(
        "orders",
        sa.Column("order_number", sa.String(length=100), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("recipient", sa.String(length=255), server_default="", nullable=False),
        sa.Column("destination", sa.Text(), server_default="", nullable=False),
        sa.Column("order_date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=30), server_default="DRAFT", nullable=False),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','CONFIRMED','MATERIALS','PRODUCTION','READY',"
            "'PARTIALLY_SHIPPED','SHIPPED','CANCELLED')",
            name=op.f("ck_orders_status"),
        ),
        sa.CheckConstraint(
            "deadline IS NULL OR deadline >= order_date", name=op.f("ck_orders_date_order")
        ),
        sa.CheckConstraint(
            "length(trim(order_number)) > 0", name=op.f("ck_orders_number_nonempty")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_orders_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_orders_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("order_number", name="uq_orders_number"),
    )
    op.create_index(op.f("ix_orders_customer_id"), "orders", ["customer_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_table(
        "procurement_records",
        sa.Column("component_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="UAH", nullable=False),
        sa.Column("order_date", sa.Date(), nullable=True),
        sa.Column("expected_date", sa.Date(), nullable=True),
        sa.Column("tracking_number", sa.String(length=255), server_default="", nullable=False),
        sa.Column("status", sa.String(length=30), server_default="REQUIRED", nullable=False),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('REQUIRED','RFQ','ORDERED','PAID','IN_TRANSIT',"
            "'CUSTOMS','RECEIVED','ISSUE')",
            name=op.f("ck_procurement_records_status"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_procurement_records_quantity_positive")),
        sa.CheckConstraint(
            "unit_price IS NULL OR unit_price >= 0",
            name=op.f("ck_procurement_records_price_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.id"],
            name=op.f("fk_procurement_records_component_id_components"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_procurement_records_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_procurement_records_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_procurement_records")),
    )
    op.create_index(
        op.f("ix_procurement_records_component_id"),
        "procurement_records",
        ["component_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procurement_records_status"), "procurement_records", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_procurement_records_supplier_id"),
        "procurement_records",
        ["supplier_id"],
        unique=False,
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("product_revision_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("required_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_items_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_order_items_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_revision_id"],
            ["product_revisions.id"],
            name=op.f("fk_order_items_product_revision_id_product_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
        sa.UniqueConstraint(
            "order_id", "product_revision_id", "required_date", name="uq_order_items_line"
        ),
    )
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    op.create_index(
        op.f("ix_order_items_product_revision_id"),
        "order_items",
        ["product_revision_id"],
        unique=False,
    )
    op.create_table(
        "order_variants",
        sa.Column("order_item_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("is_standard", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("status", sa.String(length=30), server_default="DRAFT", nullable=False),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','PENDING_APPROVAL','APPROVED','REJECTED','RELEASED')",
            name=op.f("ck_order_variants_status"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_variants_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["order_items.id"],
            name=op.f("fk_order_variants_order_item_id_order_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_variants")),
        sa.UniqueConstraint("order_item_id", "name", name="uq_order_variants_name"),
    )
    op.create_index(
        op.f("ix_order_variants_order_item_id"), "order_variants", ["order_item_id"], unique=False
    )
    op.create_index(op.f("ix_order_variants_status"), "order_variants", ["status"], unique=False)
    op.create_table(
        "variant_deviations",
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("original_bom_item_id", sa.Uuid(), nullable=False),
        sa.Column("replacement_component_id", sa.Uuid(), nullable=False),
        sa.Column("quantity_per_product", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("requested_by_id", sa.Uuid(), nullable=False),
        sa.Column("approved_by_id", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column("required_retest", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "length(trim(reason)) > 0", name=op.f("ck_variant_deviations_reason_nonempty")
        ),
        sa.CheckConstraint(
            "quantity_per_product > 0", name=op.f("ck_variant_deviations_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_id"],
            ["users.id"],
            name=op.f("fk_variant_deviations_approved_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["original_bom_item_id"],
            ["product_revision_bom_items.id"],
            name=op.f("fk_variant_deviations_original_bom_item_id_product_revision_bom_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["replacement_component_id"],
            ["components.id"],
            name=op.f("fk_variant_deviations_replacement_component_id_components"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["users.id"],
            name=op.f("fk_variant_deviations_requested_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["order_variants.id"],
            name=op.f("fk_variant_deviations_variant_id_order_variants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_variant_deviations")),
        sa.UniqueConstraint("variant_id", "original_bom_item_id", name="uq_variant_deviations_bom"),
    )
    op.create_index(
        op.f("ix_variant_deviations_replacement_component_id"),
        "variant_deviations",
        ["replacement_component_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_variant_deviations_variant_id"), "variant_deviations", ["variant_id"], unique=False
    )
    op.create_table(
        "deviation_tests",
        sa.Column("deviation_id", sa.Uuid(), nullable=False),
        sa.Column("test_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deviation_id"],
            ["variant_deviations.id"],
            name=op.f("fk_deviation_tests_deviation_id_variant_deviations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["tests.id"],
            name=op.f("fk_deviation_tests_test_id_tests"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deviation_tests")),
        sa.UniqueConstraint("deviation_id", "test_id", name="uq_deviation_tests"),
    )
    op.create_table(
        "material_requirements",
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("original_bom_item_id", sa.Uuid(), nullable=False),
        sa.Column("source_deviation_id", sa.Uuid(), nullable=True),
        sa.Column("component_id", sa.Uuid(), nullable=False),
        sa.Column("uom_id", sa.Uuid(), nullable=False),
        sa.Column("required_quantity", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "required_quantity > 0", name=op.f("ck_material_requirements_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.id"],
            name=op.f("fk_material_requirements_component_id_components"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["original_bom_item_id"],
            ["product_revision_bom_items.id"],
            name=op.f("fk_material_requirements_original_bom_item_id_product_revision_bom_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_deviation_id"],
            ["variant_deviations.id"],
            name=op.f("fk_material_requirements_source_deviation_id_variant_deviations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["uom_id"],
            ["units_of_measure.id"],
            name=op.f("fk_material_requirements_uom_id_units_of_measure"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["order_variants.id"],
            name=op.f("fk_material_requirements_variant_id_order_variants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_requirements")),
        sa.UniqueConstraint(
            "variant_id", "original_bom_item_id", name="uq_material_requirements_bom"
        ),
    )
    op.create_index(
        op.f("ix_material_requirements_component_id"),
        "material_requirements",
        ["component_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_material_requirements_variant_id"),
        "material_requirements",
        ["variant_id"],
        unique=False,
    )
    op.create_table(
        "procurement_allocations",
        sa.Column("procurement_record_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_procurement_allocations_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["procurement_record_id"],
            ["procurement_records.id"],
            name=op.f("fk_procurement_allocations_procurement_record_id_procurement_records"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["material_requirements.id"],
            name=op.f("fk_procurement_allocations_requirement_id_material_requirements"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_procurement_allocations")),
        sa.UniqueConstraint(
            "procurement_record_id", "requirement_id", name="uq_procurement_allocations"
        ),
    )
    op.create_index(
        op.f("ix_procurement_allocations_procurement_record_id"),
        "procurement_allocations",
        ["procurement_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procurement_allocations_requirement_id"),
        "procurement_allocations",
        ["requirement_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_procurement_allocations_requirement_id"), table_name="procurement_allocations"
    )
    op.drop_index(
        op.f("ix_procurement_allocations_procurement_record_id"),
        table_name="procurement_allocations",
    )
    op.drop_table("procurement_allocations")
    op.drop_index(op.f("ix_material_requirements_variant_id"), table_name="material_requirements")
    op.drop_index(op.f("ix_material_requirements_component_id"), table_name="material_requirements")
    op.drop_table("material_requirements")
    op.drop_table("deviation_tests")
    op.drop_index(op.f("ix_variant_deviations_variant_id"), table_name="variant_deviations")
    op.drop_index(
        op.f("ix_variant_deviations_replacement_component_id"), table_name="variant_deviations"
    )
    op.drop_table("variant_deviations")
    op.drop_index(op.f("ix_order_variants_status"), table_name="order_variants")
    op.drop_index(op.f("ix_order_variants_order_item_id"), table_name="order_variants")
    op.drop_table("order_variants")
    op.drop_index(op.f("ix_order_items_product_revision_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_procurement_records_supplier_id"), table_name="procurement_records")
    op.drop_index(op.f("ix_procurement_records_status"), table_name="procurement_records")
    op.drop_index(op.f("ix_procurement_records_component_id"), table_name="procurement_records")
    op.drop_table("procurement_records")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_customer_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_table("suppliers")
    op.drop_table("customers")
    # ### end Alembic commands ###
