"""phase5 production execution

Revision: 0011_phase5_execution
Revises: 0010_phase4_orders
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0011_phase5_execution"
down_revision: str | Sequence[str] | None = "0010_phase4_orders"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "production_items",
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("route_id", sa.Uuid(), nullable=False),
        sa.Column("tracking_mode", sa.String(length=20), nullable=False),
        sa.Column("identifier", sa.String(length=180), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(tracking_mode = 'SERIAL' AND quantity = 1) OR tracking_mode IN ('BATCH','QUANTITY')",
            name=op.f("ck_production_items_serial_quantity"),
        ),
        sa.CheckConstraint(
            "tracking_mode IN ('SERIAL','BATCH','QUANTITY')",
            name=op.f("ck_production_items_tracking_mode"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_production_items_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["production_routes.id"],
            name=op.f("fk_production_items_route_id_production_routes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["order_variants.id"],
            name=op.f("fk_production_items_variant_id_order_variants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_items")),
        sa.UniqueConstraint("identifier", name="uq_production_items_identifier"),
    )
    op.create_index(
        op.f("ix_production_items_route_id"), "production_items", ["route_id"], unique=False
    )
    op.create_index(
        op.f("ix_production_items_variant_id"), "production_items", ["variant_id"], unique=False
    )
    op.create_table(
        "stage_executions",
        sa.Column("production_item_id", sa.Uuid(), nullable=False),
        sa.Column("stage_id", sa.Uuid(), nullable=False),
        sa.Column("attempt", sa.Integer(), server_default="1", nullable=False),
        sa.Column("planned_quantity", sa.Integer(), nullable=False),
        sa.Column("completed_quantity", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failed_quantity", sa.Integer(), server_default="0", nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("assigned_user_id", sa.Uuid(), nullable=True),
        sa.Column("started_by_id", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by_id", sa.Uuid(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result_note", sa.Text(), server_default="", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('WAITING','READY','IN_PROGRESS','PASSED','FAILED','CANCELLED')",
            name=op.f("ck_stage_executions_status"),
        ),
        sa.CheckConstraint("attempt > 0", name=op.f("ck_stage_executions_attempt_positive")),
        sa.CheckConstraint(
            "completed_quantity + failed_quantity <= planned_quantity",
            name=op.f("ck_stage_executions_result_within_plan"),
        ),
        sa.CheckConstraint(
            "completed_quantity >= 0", name=op.f("ck_stage_executions_completed_nonnegative")
        ),
        sa.CheckConstraint(
            "failed_quantity >= 0", name=op.f("ck_stage_executions_failed_nonnegative")
        ),
        sa.CheckConstraint(
            "planned_quantity > 0", name=op.f("ck_stage_executions_planned_positive")
        ),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["users.id"],
            name=op.f("fk_stage_executions_assigned_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["completed_by_id"],
            ["users.id"],
            name=op.f("fk_stage_executions_completed_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["production_item_id"],
            ["production_items.id"],
            name=op.f("fk_stage_executions_production_item_id_production_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["route_stages.id"],
            name=op.f("fk_stage_executions_stage_id_route_stages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["started_by_id"],
            ["users.id"],
            name=op.f("fk_stage_executions_started_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_executions")),
        sa.UniqueConstraint("production_item_id", "stage_id", "attempt", name="uq_stage_attempt"),
    )
    op.create_index(
        op.f("ix_stage_executions_assigned_user_id"),
        "stage_executions",
        ["assigned_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stage_executions_production_item_id"),
        "stage_executions",
        ["production_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stage_executions_stage_id"), "stage_executions", ["stage_id"], unique=False
    )
    op.create_index(
        op.f("ix_stage_executions_status"), "stage_executions", ["status"], unique=False
    )
    op.create_table(
        "stage_checklist_results",
        sa.Column("execution_id", sa.Uuid(), nullable=False),
        sa.Column("template_item_id", sa.Uuid(), nullable=False),
        sa.Column("text_snapshot", sa.Text(), nullable=False),
        sa.Column("required_snapshot", sa.Boolean(), nullable=False),
        sa.Column("note_required_snapshot", sa.Boolean(), nullable=False),
        sa.Column("photo_required_snapshot", sa.Boolean(), nullable=False),
        sa.Column("checked", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), server_default="", nullable=False),
        sa.Column("photo_attachment_id", sa.Uuid(), nullable=True),
        sa.Column("completed_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["completed_by_id"],
            ["users.id"],
            name=op.f("fk_stage_checklist_results_completed_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["stage_executions.id"],
            name=op.f("fk_stage_checklist_results_execution_id_stage_executions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["photo_attachment_id"],
            ["attachments.id"],
            name=op.f("fk_stage_checklist_results_photo_attachment_id_attachments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_item_id"],
            ["checklist_template_items.id"],
            name=op.f("fk_stage_checklist_results_template_item_id_checklist_template_items"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_checklist_results")),
        sa.UniqueConstraint("execution_id", "template_item_id", name="uq_execution_checklist_item"),
    )
    op.create_index(
        op.f("ix_stage_checklist_results_execution_id"),
        "stage_checklist_results",
        ["execution_id"],
        unique=False,
    )
    op.create_table(
        "stage_events",
        sa.Column("execution_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("reason", sa.Text(), server_default="", nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('START','PASS','FAIL','RETURN','CANCEL')",
            name=op.f("ck_stage_events_type"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_stage_events_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_stage_events_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["stage_executions.id"],
            name=op.f("fk_stage_events_execution_id_stage_executions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_events")),
        sa.UniqueConstraint("idempotency_key", name="uq_stage_events_idempotency_key"),
    )
    op.create_index(
        op.f("ix_stage_events_execution_id"), "stage_events", ["execution_id"], unique=False
    )
    op.add_column("attachments", sa.Column("stage_execution_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_attachments_stage_execution_id"),
        "attachments",
        ["stage_execution_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_attachments_stage_execution_id_stage_executions"),
        "attachments",
        "stage_executions",
        ["stage_execution_id"],
        ["id"],
        ondelete="RESTRICT",
        use_alter=True,
    )
    op.drop_constraint(op.f("ck_attachments_one_owner"), "attachments", type_="check")
    op.create_check_constraint(
        op.f("ck_attachments_one_owner"),
        "attachments",
        "num_nonnulls(project_id, task_id, setup_id, component_id, test_id, "
        "firmware_revision_id, branch_id, product_id, product_revision_id, "
        "firmware_release_id, stage_execution_id) = 1",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_attachments_stage_execution_id_stage_executions"),
        "attachments",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_attachments_stage_execution_id"), table_name="attachments")
    op.drop_constraint(op.f("ck_attachments_one_owner"), "attachments", type_="check")
    op.drop_column("attachments", "stage_execution_id")
    op.create_check_constraint(
        op.f("ck_attachments_one_owner"),
        "attachments",
        "num_nonnulls(project_id, task_id, setup_id, component_id, test_id, "
        "firmware_revision_id, branch_id, product_id, product_revision_id, "
        "firmware_release_id) = 1",
    )
    op.drop_index(op.f("ix_stage_events_execution_id"), table_name="stage_events")
    op.drop_table("stage_events")
    op.drop_index(
        op.f("ix_stage_checklist_results_execution_id"), table_name="stage_checklist_results"
    )
    op.drop_table("stage_checklist_results")
    op.drop_index(op.f("ix_stage_executions_status"), table_name="stage_executions")
    op.drop_index(op.f("ix_stage_executions_stage_id"), table_name="stage_executions")
    op.drop_index(op.f("ix_stage_executions_production_item_id"), table_name="stage_executions")
    op.drop_index(op.f("ix_stage_executions_assigned_user_id"), table_name="stage_executions")
    op.drop_table("stage_executions")
    op.drop_index(op.f("ix_production_items_variant_id"), table_name="production_items")
    op.drop_index(op.f("ix_production_items_route_id"), table_name="production_items")
    op.drop_table("production_items")
    # ### end Alembic commands ###
