import { Fragment, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { api, send } from '../../api/client'
import { ErrorNotice, Field, Loading } from '../../components/Feedback'
import { StatusBadge } from '../../components/StatusBadge'
import { Button } from '../../components/ui/button'
import { Input } from '../../components/ui/input'
import { hasCapability } from '../auth/types'
import { useSession } from '../auth/useSession'
import type { BomItem, ComponentOption, Deviation, MaterialSummary, Order, OrderItem, OrderProgress, OrderVariant, ProcurementAllocation, ProcurementRecord, Requirement, RequirementPreviewRow, RevisionOption } from './types'

const tabs = ['Огляд', 'Вироби', 'Комплектуючі', 'Закупівлі', 'Виробництво', 'Відвантаження'] as const

export function OrderDetail() {
  const { id = '' } = useParams(), cache = useQueryClient(), [tab, setTab] = useState<(typeof tabs)[number]>('Огляд')
  const { data: user } = useSession(), canManage = hasCapability(user, 'MANAGE_ORDERS'), canApprove = hasCapability(user, 'APPROVE_DEVIATIONS')
  const order = useQuery({ queryKey: ['order', id], queryFn: ({ signal }) => api<Order>(`/orders/${id}`, { signal }) })
  const items = useQuery({ queryKey: ['order-items', id], queryFn: ({ signal }) => api<OrderItem[]>(`/orders/${id}/items`, { signal }) })
  const revisions = useQuery({ queryKey: ['released-revisions'], queryFn: ({ signal }) => api<RevisionOption[]>('/orders/revision-options', { signal }) })
  const requirements = useQuery({ queryKey: ['requirements', id], queryFn: ({ signal }) => api<Requirement[]>(`/orders/${id}/requirements`, { signal }) })
  const materials = useQuery({ queryKey: ['materials', id], queryFn: ({ signal }) => api<MaterialSummary[]>(`/orders/${id}/materials`, { signal }) })
  const progress = useQuery({ queryKey: ['production-progress', id], queryFn: ({ signal }) => api<OrderProgress>(`/production/orders/${id}/progress`, { signal }), enabled: order.data?.status === 'PRODUCTION' || order.data?.status === 'READY' })
  const transition = useMutation({ mutationFn: (status: string) => send<Order>(`/orders/${id}/status`, 'POST', { status, expected_draft_version: order.data?.draft_version }), onSuccess: async () => cache.invalidateQueries({ queryKey: ['order', id] }) })
  const launch = useMutation({ mutationFn: () => send<{ created_items: number }>(`/production/orders/${id}/launch`, 'POST'), onSuccess: async () => { await Promise.all([cache.invalidateQueries({ queryKey: ['order', id] }), cache.invalidateQueries({ queryKey: ['production-items', id] }), cache.invalidateQueries({ queryKey: ['production-progress', id] })]) } })
  if (order.isPending || items.isPending) return <Loading />
  if (!order.data) return <ErrorNotice error={order.error} />
  const overdue = Boolean(order.data.deadline && order.data.deadline < new Date().toISOString().slice(0, 10) && !['READY', 'SHIPPED', 'CANCELLED'].includes(order.data.status))
  const covered = materials.data?.filter(row => Number(row.launch_shortage) === 0).length ?? 0
  return <><Link className="back-link" to="/orders">← До замовлень</Link><div className="page-heading"><div><p className="eyebrow">ЗАМОВЛЕННЯ</p><h1>{order.data.order_number}</h1><p className="page-description">{order.data.customer_name} · {order.data.recipient || 'отримувача не вказано'}</p></div><div><StatusBadge value={order.data.status} />{overdue && <p className="field-error">Строк виконання минув</p>}</div></div>
    {canManage && <div className="form-actions">{order.data.status === 'DRAFT' && <Button onClick={() => transition.mutate('CONFIRMED')}>Підтвердити замовлення</Button>}{order.data.status === 'CONFIRMED' && <Button onClick={() => transition.mutate('MATERIALS')}>Передати в матеріали</Button>}{order.data.status === 'MATERIALS' && <Button onClick={() => launch.mutate()} disabled={launch.isPending}>Запустити виробництво</Button>}</div>}<ErrorNotice error={transition.error || launch.error || items.error || revisions.error} />
    <div className="tabs">{tabs.map(value => <button key={value} className={tab === value ? 'selected' : ''} onClick={() => setTab(value)}>{value}</button>)}</div>
    {tab === 'Огляд' && <dl className="detail-grid"><div><dt>Замовник</dt><dd>{order.data.customer_name}</dd></div><div><dt>Дата</dt><dd>{order.data.order_date}</dd></div><div><dt>Строк</dt><dd>{order.data.deadline ?? 'Не встановлено'}</dd></div><div><dt>Отримувач</dt><dd>{order.data.recipient || 'Не вказано'}</dd></div><div><dt>Вироби</dt><dd>{items.data?.reduce((sum, item) => sum + item.quantity, 0) ?? 0} од.</dd></div><div><dt>Матеріали</dt><dd>{materials.data?.length ? `${covered} з ${materials.data.length} позицій покрито` : 'Специфікацію ще не зафіксовано'}</dd></div></dl>}
    {tab === 'Вироби' && <section>{order.data.status === 'DRAFT' && canManage && revisions.data && <AddItem orderId={id} revisions={revisions.data} />}{items.data?.map(item => <ItemCard key={item.id} item={item} orderId={id} editable={order.data.status === 'DRAFT' && canManage} canApprove={canApprove} />)}{!items.data?.length && <div className="empty-state"><p>Додайте першу позицію із затвердженої версії продукції.</p></div>}</section>}
    {tab === 'Комплектуючі' && <Materials requirements={requirements.data ?? []} rows={materials.data ?? []} title="Ефективна специфікація замовлення" />}
    {tab === 'Закупівлі' && <OrderProcurement orderId={id} requirements={requirements.data ?? []} materials={materials.data ?? []} canManage={hasCapability(user, 'MANAGE_PROCUREMENT')} />}
    {tab === 'Виробництво' && (progress.data ? <section><div className="section-heading"><h2>Стан виробництва</h2><span>{progress.data.percent}%</span></div><div className="progress-block"><progress max={100} value={progress.data.percent} /><span>{progress.data.completed} з {progress.data.total} операцій виконано</span></div><Link className="record-link" to={`/production/orders/${id}/execution`}>Відкрити у виробництві →</Link></section> : <div className="empty-state"><p>Виробництво ще не запущено.</p></div>)}
    {tab === 'Відвантаження' && <div className="empty-state"><h2>Відвантаження</h2><p>Облік відвантаження ще не реалізований.</p></div>}
  </>
}

function AddItem({ orderId, revisions }: { orderId: string; revisions: RevisionOption[] }) {
  const cache = useQueryClient(), products = [...new Map(revisions.map(row => [row.product_id, row.product_name])).entries()]
  const [productId, setProductId] = useState(products[0]?.[0] ?? ''), productRevisions = revisions.filter(row => row.product_id === productId)
  const variants = [...new Map(productRevisions.map(row => [row.variant_id, row.variant_name])).entries()]
  const [variantId, setVariantId] = useState(''), activeVariantId = variants.some(([id]) => id === variantId) ? variantId : variants[0]?.[0] ?? ''
  const variantRevisions = productRevisions.filter(row => row.variant_id === activeVariantId)
  const [revisionId, setRevisionId] = useState(''), activeRevisionId = variantRevisions.some(row => row.id === revisionId) ? revisionId : variantRevisions[0]?.id ?? ''
  const [quantity, setQuantity] = useState(1)
  const preview = useQuery({ queryKey: ['requirement-preview', activeRevisionId, quantity], queryFn: ({ signal }) => api<RequirementPreviewRow[]>(`/orders/requirements/preview?product_revision_id=${activeRevisionId}&quantity=${quantity}`, { signal }), enabled: Boolean(activeRevisionId && quantity > 0) })
  const mutation = useMutation({ mutationFn: () => send<OrderItem>(`/orders/${orderId}/items`, 'POST', { product_revision_id: activeRevisionId, quantity, required_date: null, notes: '' }), onSuccess: async () => Promise.all([cache.invalidateQueries({ queryKey: ['order-items', orderId] }), cache.invalidateQueries({ queryKey: ['order', orderId] })]) })
  return <form className="form-panel form-stack" onSubmit={event => { event.preventDefault(); mutation.mutate() }}><h2>Додати виріб</h2><div className="editor-grid"><Field label="Модель"><select className="form-input" value={productId} onChange={event => { setProductId(event.target.value); setVariantId(''); setRevisionId('') }}>{products.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></Field><Field label="Комплектація"><select className="form-input" value={activeVariantId} onChange={event => { setVariantId(event.target.value); setRevisionId('') }}>{variants.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></Field><Field label="Затверджена версія"><select className="form-input" value={activeRevisionId} onChange={event => setRevisionId(event.target.value)}>{variantRevisions.map(row => <option key={row.id} value={row.id}>{row.revision_code}</option>)}</select></Field><Field label="Кількість"><Input type="number" min={1} value={quantity} onChange={event => setQuantity(Number(event.target.value))} /></Field></div><ErrorNotice error={mutation.error || preview.error} />{preview.data && <RequirementPreview rows={preview.data} />}<Button type="submit" disabled={mutation.isPending || !activeRevisionId}>Додати позицію</Button></form>
}

function RequirementPreview({ rows }: { rows: RequirementPreviewRow[] }) {
  return <div className="table-scroll"><table><thead><tr><th>Позиція</th><th>Компонент</th><th>На виріб</th><th>Всього</th></tr></thead><tbody>{rows.map(row => <Fragment key={row.bom_item_id}><tr><td>{row.position || '—'}</td><td>{row.component_name}{row.component_sku && ` · ${row.component_sku}`}</td><td>{row.quantity_per_product} {row.uom_code}</td><td>{row.total_quantity} {row.uom_code}</td></tr>{row.alternatives.map(alternative => <tr className="substitution-row" key={alternative.component_id}><td>↳ Альтернатива</td><td colSpan={3}>{alternative.component_name}{alternative.component_sku && ` · ${alternative.component_sku}`}{alternative.notes && ` — ${alternative.notes}`}</td></tr>)}</Fragment>)}</tbody></table></div>
}

function ItemCard({ item, orderId, editable, canApprove }: { item: OrderItem; orderId: string; editable: boolean; canApprove: boolean }) {
  const cache = useQueryClient(), [name, setName] = useState(''), [quantity, setQuantity] = useState(1)
  const variants = useQuery({ queryKey: ['variants', item.id], queryFn: ({ signal }) => api<OrderVariant[]>(`/orders/items/${item.id}/variants`, { signal }) })
  const refresh = async () => Promise.all([cache.invalidateQueries({ queryKey: ['variants', item.id] }), cache.invalidateQueries({ queryKey: ['order', orderId] })])
  const split = useMutation({ mutationFn: () => send<OrderVariant>(`/orders/items/${item.id}/variants`, 'POST', { name, quantity, notes: '' }), onSuccess: async () => { setName(''); await refresh() } })
  const release = useMutation({ mutationFn: () => send<OrderVariant[]>(`/orders/items/${item.id}/release-variants`, 'POST'), onSuccess: async () => { await Promise.all([refresh(), cache.invalidateQueries({ queryKey: ['requirements', orderId] }), cache.invalidateQueries({ queryKey: ['materials', orderId] })]) } })
  return <article className="operation-card"><div className="view-controls"><div><h3>{item.product_name} · {item.revision_code}</h3><p>{item.quantity} од. · версію зафіксовано</p></div>{editable && <Button onClick={() => release.mutate()} disabled={release.isPending}>Зафіксувати специфікацію</Button>}</div><ErrorNotice error={variants.error || split.error || release.error} />
    {editable && <form className="filters" onSubmit={e => { e.preventDefault(); split.mutate() }}><Input required placeholder="Назва варіанта замовлення" value={name} onChange={e => setName(e.target.value)} /><Input type="number" min={1} max={item.quantity - 1} value={quantity} onChange={e => setQuantity(Number(e.target.value))} /><Button type="submit" disabled={split.isPending || item.quantity < 2}>Розділити кількість</Button></form>}
    {variants.data?.map(variant => <VariantRow key={variant.id} variant={variant} revisionId={item.product_revision_id} itemId={item.id} orderId={orderId} editable={editable} canApprove={canApprove} />)}
  </article>
}

function VariantRow({ variant, revisionId, itemId, orderId, editable, canApprove }: { variant: OrderVariant; revisionId: string; itemId: string; orderId: string; editable: boolean; canApprove: boolean }) {
  const cache = useQueryClient(), [show, setShow] = useState(false), [bomId, setBomId] = useState(''), [componentId, setComponentId] = useState(''), [reason, setReason] = useState(''), [quantity, setQuantity] = useState('1')
  const bom = useQuery({ queryKey: ['bom', revisionId], queryFn: ({ signal }) => api<BomItem[]>(`/products/revisions/${revisionId}/bom`, { signal }) })
  const components = useQuery({ queryKey: ['component-options'], queryFn: ({ signal }) => api<ComponentOption[]>('/components/options', { signal }), enabled: show })
  const deviations = useQuery({ queryKey: ['deviations', variant.id], queryFn: ({ signal }) => api<Deviation[]>(`/orders/variants/${variant.id}/deviations`, { signal }) })
  const refresh = async () => Promise.all([cache.invalidateQueries({ queryKey: ['deviations', variant.id] }), cache.invalidateQueries({ queryKey: ['variants', itemId] }), cache.invalidateQueries({ queryKey: ['order', orderId] })])
  const add = useMutation({ mutationFn: () => send<Deviation>(`/orders/variants/${variant.id}/deviations`, 'POST', { original_bom_item_id: bomId, replacement_component_id: componentId, quantity_per_product: quantity, reason, required_retest: false, test_ids: [], notes: '' }), onSuccess: async () => { setShow(false); await refresh() } })
  const decide = useMutation({ mutationFn: ({ id, action }: { id: string; action: 'approve' | 'reject' }) => send<Deviation>(`/orders/deviations/${id}/${action}`, 'POST'), onSuccess: refresh })
  const componentName = (id: string) => components.data?.find(row => row.id === id)?.name ?? 'Компонент'
  return <div className="variant-row"><div><strong>{variant.name}</strong> · {variant.quantity} од. <StatusBadge value={variant.status} /></div>{editable && !variant.is_standard && variant.status === 'DRAFT' && <Button onClick={() => setShow(v => !v)}>Запросити заміну</Button>}{show && <form className="form-panel form-stack" onSubmit={e => { e.preventDefault(); add.mutate() }}><Field label="Позиція специфікації"><select required className="form-input" value={bomId} onChange={e => setBomId(e.target.value)}><option value="">Оберіть позицію</option>{bom.data?.map(row => <option key={row.id} value={row.id}>{row.position || componentName(row.component_id)} · {componentName(row.component_id)}</option>)}</select></Field><Field label="Компонент заміни"><select required className="form-input" value={componentId} onChange={e => setComponentId(e.target.value)}><option value="">Оберіть компонент</option>{components.data?.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></Field><Field label="Кількість на виріб"><Input type="number" min="0.0001" step="0.0001" value={quantity} onChange={e => setQuantity(e.target.value)} /></Field><Field label="Причина"><Input required value={reason} onChange={e => setReason(e.target.value)} /></Field><ErrorNotice error={add.error} /><Button type="submit" disabled={add.isPending}>Надіслати на погодження</Button></form>}{deviations.data?.map(row => <div className="activity-row" key={row.id}><span><strong>{componentName(row.replacement_component_id)}</strong> замість {componentName(bom.data?.find(item => item.id === row.original_bom_item_id)?.component_id ?? '')} · {row.quantity_per_product} на виріб · {row.reason}</span>{canApprove && !row.approved_at && variant.status === 'PENDING_APPROVAL' && <span className="form-actions"><Button onClick={() => decide.mutate({ id: row.id, action: 'approve' })}>Погодити</Button><Button onClick={() => decide.mutate({ id: row.id, action: 'reject' })}>Відхилити</Button></span>}</div>)}</div>
}

function Materials({ requirements, rows, title }: { requirements: Requirement[]; rows: MaterialSummary[]; title: string }) {
  return <section><div className="section-heading"><h2>{title}</h2><span>{rows.filter(row => Number(row.launch_shortage) === 0).length} / {rows.length} готово</span></div>{rows.length ? <div className="table-scroll"><table><thead><tr><th>Компонент</th><th>Потрібно</th><th>Отримано під замовлення</th><th>Замовлено</th><th>У дорозі</th><th>Не покрито закупівлею</th><th>Бракує для запуску</th></tr></thead><tbody>{rows.map(row => <tr key={`${row.component_id}-${row.uom_id}`}><td>{row.component_name || requirements.find(requirement => requirement.component_id === row.component_id)?.component_name || 'Компонент'}</td><td>{row.required} {row.uom_code}</td><td>{row.received} {row.uom_code}</td><td>{row.ordered} {row.uom_code}</td><td>{row.in_transit} {row.uom_code}</td><td>{row.uncovered} {row.uom_code}</td><td>{row.launch_shortage} {row.uom_code}</td></tr>)}</tbody></table></div> : <div className="empty-state"><p>Зафіксуйте специфікацію варіантів, щоб побачити потребу.</p></div>}</section>
}

function OrderProcurement({ orderId, requirements, materials, canManage }: { orderId: string; requirements: Requirement[]; materials: MaterialSummary[]; canManage: boolean }) {
  const cache = useQueryClient(), [recordId, setRecordId] = useState(''), [requirementId, setRequirementId] = useState(''), [quantity, setQuantity] = useState('1')
  const records = useQuery({ queryKey: ['procurement', 'allocation-options'], queryFn: ({ signal }) => api<{ items: ProcurementRecord[] }>('/procurement?page=1&page_size=100', { signal }) })
  const allocation = useMutation({ mutationFn: () => send<ProcurementAllocation>(`/procurement/${recordId}/allocations`, 'POST', { requirement_id: requirementId, quantity }), onSuccess: async () => { await Promise.all([cache.invalidateQueries({ queryKey: ['materials', orderId] }), cache.invalidateQueries({ queryKey: ['order', orderId] }), cache.invalidateQueries({ queryKey: ['procurement'] })]) } })
  const selectedRequirement = requirements.find(row => row.id === requirementId)
  const matchingRecords = records.data?.items.filter(row => row.component_id === selectedRequirement?.component_id && row.uom_id === selectedRequirement?.uom_id) ?? []
  return <><Materials requirements={requirements} rows={materials} title="Покриття потреби" />{canManage && requirements.length > 0 && <form className="form-panel editor-grid" onSubmit={event => { event.preventDefault(); allocation.mutate() }}><Field label="Потреба замовлення"><select required className="form-input" value={requirementId} onChange={event => { setRequirementId(event.target.value); setRecordId('') }}><option value="">Оберіть позицію</option>{requirements.map(row => <option key={row.id} value={row.id}>{row.component_name} · {row.required_quantity}</option>)}</select></Field><Field label="Закупівля"><select required className="form-input" value={recordId} onChange={event => setRecordId(event.target.value)}><option value="">Оберіть закупівлю</option>{matchingRecords.map(row => <option key={row.id} value={row.id}>{row.component_name} · {row.quantity} {row.uom_code}</option>)}</select></Field><Field label="Кількість для замовлення"><Input type="number" min="0.0001" step="0.0001" value={quantity} onChange={event => setQuantity(event.target.value)} /></Field><ErrorNotice error={records.error || allocation.error} /><Button type="submit" disabled={allocation.isPending || !recordId || !requirementId}>Прив’язати закупівлю</Button></form>}</>
}
