"""Freeze the installed, verified backend dependency graph without local paths.

Run after installing backend[dev]. Keeps runtime and development locks separate.
Includes platform-marked dependencies for Linux and Windows for container parity.
"""

from importlib.metadata import distribution
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT = Path(__file__).resolve().parents[1]


def dependency_graph(roots: list[str]) -> dict[str, str]:
    resolved: dict[str, str] = {}
    seen: set[tuple[str, tuple[str, ...]]] = set()
    pending = [Requirement(root) for root in roots]
    while pending:
        requirement = pending.pop()
        key = (canonicalize_name(requirement.name), tuple(sorted(requirement.extras)))
        if key in seen:
            continue
        seen.add(key)
        package = distribution(requirement.name)
        resolved[canonicalize_name(package.metadata["Name"])] = package.version
        for dependency in package.requires or []:
            child = Requirement(dependency)
            environments = [
                {"extra": extra, "sys_platform": platform, "os_name": os_name}
                for extra in ("", *requirement.extras)
                for platform, os_name in (("win32", "nt"), ("linux", "posix"))
            ]
            if child.marker is None or any(
                child.marker.evaluate(env) for env in environments
            ):
                pending.append(child)
    return resolved


def write_lock(filename: str, packages: dict[str, str]) -> None:
    header = "# Generated by scripts/lock_backend.py from the verified environment.\n"
    lines = [f"{name}=={version}" for name, version in sorted(packages.items())]
    (ROOT / "backend" / filename).write_text(
        header + "\n".join(lines) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    application = distribution("baza-backend")
    runtime = [
        item
        for item in application.requires or []
        if Requirement(item).marker is None
        or Requirement(item).marker.evaluate({"extra": ""})
    ]
    # Setuptools is needed by the Docker image's --no-build-isolation package install.
    write_lock("requirements.lock", dependency_graph([*runtime, "setuptools"]))
    development = [
        item
        for item in application.requires or []
        if Requirement(item).marker is None
        or Requirement(item).marker.evaluate({"extra": "dev"})
    ]
    write_lock("requirements-dev.lock", dependency_graph([*development, "setuptools"]))
