import { expect, test } from '@playwright/test'
import process from 'node:process'

test('Phase 1–2 workflow through R&D promotion and logout', async ({ page }) => {
  test.setTimeout(300_000)
  const username = process.env.E2E_USERNAME, password = process.env.E2E_PASSWORD
  if (!username || !password) throw new Error('Run through scripts/run_e2e.py with an isolated database')
  await page.goto('/')
  await page.getByLabel('Логін', { exact: true }).fill(username)
  await page.getByLabel('Пароль', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Увійти', exact: true }).click()
  await expect(page.getByText('E2E Admin', { exact: true })).toBeVisible()
  const mainNavigation = page.getByRole('navigation', { name: 'Основні розділи' })
  for (const section of ['Розробка', 'Продукція', 'Замовлення', 'Виробництво', 'Склад']) {
    await expect(mainNavigation.getByRole('link', { name: section, exact: true })).toBeVisible()
  }
  await page.goto('/orders')
  await expect(page.getByRole('heading', { name: 'Замовлення', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Нове замовлення', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Закупівлі', exact: true })).toBeVisible()
  await expect(page.getByText('Замовників ще немає.', { exact: true })).toBeVisible()
  await expect(page.getByText('Замовлень не знайдено.', { exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/orders-desktop.png', fullPage: true })
  await page.goto('/production')
  await expect(page.getByRole('heading', { name: 'Виробництво', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Відкрити мою роботу →', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Нове замовлення', exact: true })).toHaveCount(0)
  await page.screenshot({ path: 'test-results/production-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 768, height: 900 })
  await expect(mainNavigation).toBeVisible()
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/projects/new')
  await page.getByLabel('Назва', { exact: true }).fill('Browser project')
  await page.getByLabel('Опис', { exact: true }).fill('Created through the real API')
  await page.getByRole('button', { name: 'Зберегти проєкт' }).click()
  await expect(page.getByRole('heading', { name: 'Browser project', exact: true })).toBeVisible()
  const projectUrl = page.url()
  await page.goto('/components/new')
  await page.getByLabel('Назва', { exact: true }).fill('Browser motor')
  await page.getByLabel('Виробник', { exact: true }).fill('E2E Motors')
  await page.getByLabel('Модель', { exact: true }).fill('M1')
  await page.getByLabel('KV (об/хв/В)', { exact: true }).fill('1200')
  await page.getByLabel('Робоча напруга', { exact: true }).fill('12S')
  await page.getByLabel('Рекомендовані пропелери', { exact: true }).fill('15.5x5.8, 17x6')
  await page.getByRole('button', { name: 'Зберегти компонент' }).click()
  await expect(page.getByRole('heading', { name: 'Browser motor', exact: true })).toBeVisible()
  const componentUrl = page.url()
  await page.goto('/setups/new')
  await page.getByLabel('Назва', { exact: true }).fill('Browser setup')
  await page.getByLabel('Клас дрона', { exact: true }).fill('15 inch')
  await page.getByLabel('Версія конфігурації', { exact: true }).fill('V1')
  await page.getByLabel('Тип прошивки', { exact: true }).fill('ArduPilot')
  await page.getByLabel('Версія прошивки', { exact: true }).fill('4.5')
  await page.getByRole('button', { name: 'Зберегти сетап' }).click()
  await expect(page.getByRole('heading', { name: 'Browser setup · V1', exact: true })).toBeVisible()
  const setupUrl = page.url()
  await page.getByRole('tab', { name: 'Компоненти', exact: true }).click()
  await page.getByRole('combobox', { name: 'Компонент', exact: true }).selectOption({ label: 'Browser motor · E2E Motors M1' })
  await page.getByLabel('Кількість', { exact: true }).fill('4')
  await page.getByLabel('Позиція', { exact: true }).fill('arms')
  await page.getByRole('button', { name: 'Додати до складу' }).click()
  await expect(page.getByRole('link', { name: 'Browser motor', exact: true })).toBeVisible()
  await page.goto(componentUrl)
  await expect(page.getByRole('link', { name: 'Browser setup', exact: true })).toBeVisible()
  await page.goto(setupUrl)
  await page.getByRole('tab', { name: 'Прошивка', exact: true }).click()
  await page.getByLabel('Назва ревізії', { exact: true }).fill('Rev A')
  await page.getByLabel('Опис', { exact: true }).fill('Initial bench configuration')
  await page.getByLabel('Текст конфігурації', { exact: true }).fill('MOT_SPIN_ARM=0.1')
  await page.getByRole('button', { name: 'Створити ревізію' }).click()
  await expect(page.getByRole('cell', { name: 'Rev A', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/setup-firmware-desktop.png', fullPage: true })
  await page.getByRole('tab', { name: 'Огляд', exact: true }).click()
  await page.getByLabel('Нова версія сетапу').fill('V2')
  await page.getByRole('button', { name: 'Створити копію', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Browser setup · V2', exact: true })).toBeVisible()
  const candidateSetupUrl = page.url()
  await page.goto(projectUrl)
  await page.getByRole('tab', { name: 'Конфігурації', exact: true }).click()
  await page.getByLabel('Сетап для проєкту', { exact: true }).selectOption({ label: 'Browser setup · V1' })
  await page.getByRole('button', { name: 'Прив’язати', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Browser setup', exact: true })).toBeVisible()
  await page.getByLabel('Сетап для проєкту', { exact: true }).selectOption({ label: 'Browser setup · V2' })
  await page.getByRole('button', { name: 'Прив’язати', exact: true }).click()
  await expect(page.getByRole('cell', { name: 'V2', exact: true })).toBeVisible()
  const projectId = projectUrl.split('/').pop()
  const setupId = setupUrl.split('/').pop()
  const candidateSetupId = candidateSetupUrl.split('/').pop()
  const componentId = componentUrl.split('/').pop()
  if (!projectId || !setupId || !candidateSetupId || !componentId) throw new Error('Expected entity identifiers in detail URLs')

  await page.getByRole('tab', { name: 'Гілки', exact: true }).click()
  await page.getByRole('button', { name: 'Нова гілка', exact: true }).click()
  await page.getByLabel('Назва', { exact: true }).fill('main')
  await page.getByLabel('Мета гілки', { exact: true }).fill('Baseline research')
  await page.getByRole('button', { name: 'Створити гілку', exact: true }).click()
  await expect(page.getByRole('link', { name: 'main', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Нова гілка', exact: true }).click()
  await page.getByLabel('Назва', { exact: true }).fill('candidate-v2')
  const parentBranch = page.getByRole('combobox', { name: 'Батьківська гілка', exact: true })
  await expect(parentBranch).toBeVisible()
  await parentBranch.selectOption({ label: 'main' })
  await page.getByLabel('Мета гілки', { exact: true }).fill('Validate candidate configuration')
  await page.getByRole('button', { name: 'Створити гілку', exact: true }).click()
  await page.getByRole('link', { name: 'candidate-v2', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'candidate-v2', exact: true })).toBeVisible()
  const branchUrl = page.url()
  const branchId = branchUrl.split('/').pop()
  if (!branchId) throw new Error('Expected branch identifier in detail URL')
  await page.getByRole('tab', { name: 'Конфігурації', exact: true }).click()
  await page.getByLabel('Конфігурація', { exact: true }).selectOption(setupId)
  await page.getByLabel('Роль конфігурації', { exact: true }).selectOption('BASELINE')
  await page.getByRole('button', { name: 'Додати', exact: true }).click()
  await expect(page.getByRole('cell', { name: 'Базова', exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('tab', { name: 'Конфігурації', exact: true }).click()
  await page.getByLabel('Конфігурація', { exact: true }).selectOption(candidateSetupId)
  await page.getByLabel('Роль конфігурації', { exact: true }).selectOption('CANDIDATE')
  await page.getByRole('button', { name: 'Додати', exact: true }).click()
  await expect(page.getByRole('cell', { name: 'Кандидат', exact: true })).toBeVisible()
  const comparison = await page.request.get(`/api/rnd/branches/${branchId}/comparison?candidate_setup_id=${candidateSetupId}`)
  expect(comparison.status()).toBe(200)
  expect((await comparison.json()).candidate.id).toBe(candidateSetupId)

  const csrf = (await page.context().cookies()).find(cookie => cookie.name === 'baza_csrf')?.value
  if (!csrf) throw new Error('Expected CSRF cookie after login')
  const writeHeaders = { 'X-CSRF-Token': csrf, Origin: 'http://127.0.0.1:4173' }
  const branchTask = await page.request.post('/api/tasks', { headers: writeHeaders, data: { title: 'Branch task', project_id: projectId, branch_id: branchId } })
  expect(branchTask.status()).toBe(201)
  const branchTest = await page.request.post('/api/tests', { headers: writeHeaders, data: { name: 'Branch evidence', test_type: 'OTHER', project_id: projectId, branch_id: branchId } })
  expect(branchTest.status()).toBe(201)
  const branchFile = await page.request.post('/api/files', { headers: writeHeaders, multipart: { branch_id: branchId, upload: { name: 'branch-evidence.txt', mimeType: 'text/plain', buffer: Buffer.from('candidate approved evidence') } } })
  expect(branchFile.status()).toBe(201)

  await page.goto(branchUrl)
  await page.getByRole('tab', { name: 'Задачі', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Branch task', exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'Випробування', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Branch evidence', exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'Файли', exact: true }).click()
  await expect(page.getByRole('cell', { name: 'branch-evidence.txt', exact: true })).toBeVisible()

  const promotion = await page.request.post(`/api/rnd/branches/${branchId}/promotion-requests`, { headers: writeHeaders, data: { candidate_setup_id: candidateSetupId, reason: 'Candidate passed branch verification' } })
  expect(promotion.status()).toBe(201)
  const promotionId = (await promotion.json()).id
  const review = await page.request.post(`/api/rnd/promotion-requests/${promotionId}/review`, { headers: writeHeaders, data: { status: 'APPROVED', review_notes: 'Approved in E2E' } })
  expect(review.status()).toBe(200)
  await page.reload()
  await page.getByRole('tab', { name: 'Затвердження', exact: true }).click()
  await expect(page.getByText('Approved in E2E', { exact: false })).toBeVisible()

  await page.goto(`/tests/new?project_id=${projectId}&setup_id=${setupId}&component_id=${componentId}&test_type=MOTOR_BENCH`)
  await expect(page.getByRole('heading', { name: 'Нове випробування' })).toBeVisible()
  await page.getByLabel('Назва', { exact: true }).fill('Browser motor test')
  await expect(page.getByRole('combobox', { name: 'Проєкт', exact: true })).toHaveValue(projectId)
  await expect(page.getByRole('combobox', { name: 'Сетап', exact: true })).toHaveValue(setupId)
  await expect(page.getByRole('combobox', { name: 'Основний компонент', exact: true })).toHaveValue(componentId)
  await page.getByRole('button', { name: 'Зберегти випробування' }).click()
  await expect(page.getByRole('heading', { name: 'Browser motor test', exact: true })).toBeVisible()
  await page.getByLabel('Газ (%)', { exact: true }).fill('50')
  await page.getByLabel('Струм (А)', { exact: true }).fill('22.5')
  await page.getByLabel('Потужність (Вт)', { exact: true }).fill('540')
  await page.getByLabel('Тяга (кг)', { exact: true }).fill('3.2')
  await page.getByRole('button', { name: 'Додати точку', exact: true }).click()
  await expect(page.getByRole('cell', { name: '22.5000', exact: true })).toBeVisible()
  await page.getByLabel('Оберіть файл').setInputFiles({ name: 'motor-result.csv', mimeType: 'text/csv', buffer: Buffer.from('throttle,current\n50,22.5\n') })
  await page.getByRole('button', { name: 'Завантажити файл' }).click()
  await expect(page.getByRole('cell', { name: 'motor-result.csv', exact: true })).toBeVisible()
  await page.getByLabel('Текст коментаря').fill('Motor bench result reviewed')
  await page.getByRole('button', { name: 'Додати коментар' }).click()
  await expect(page.getByText('Motor bench result reviewed', { exact: true })).toBeVisible()
  await page.getByLabel('Глобальний пошук').fill('Browser motor test')
  await page.getByRole('button', { name: 'Знайти', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Browser motor test', exact: true })).toBeVisible()
  await page.goto('/tasks/new')
  await page.getByLabel('Назва задачі', { exact: true }).fill('Browser task')
  await page.getByRole('combobox', { name: 'Проєкт', exact: true }).selectOption({ label: 'Browser project' })
  await page.getByRole('combobox', { name: 'Виконавець', exact: true }).selectOption({ label: 'E2E Admin' })
  await page.getByRole('button', { name: 'Зберегти задачу' }).click()
  await expect(page.getByRole('heading', { name: 'Browser task', exact: true })).toBeVisible()
  const taskUrl = page.url()
  await page.getByRole('combobox', { name: 'Статус задачі', exact: true }).selectOption('IN_PROGRESS')
  await page.getByLabel('Результат виконання').fill('Verified persistent result')
  const saved = page.waitForResponse(r => r.url().includes('/api/tasks/') && r.request().method() === 'PATCH' && r.ok())
  await page.getByRole('button', { name: 'Зберегти результат' }).click()
  await saved
  await page.reload()
  await expect(page.getByLabel('Результат виконання')).toHaveValue('Verified persistent result')
  await page.goto('/tasks')
  await page.getByRole('button', { name: 'Kanban', exact: true }).click()
  await page.getByLabel('Статус: Browser task', { exact: true }).selectOption('BLOCKED')
  const blocked = page.locator('.kanban-column').filter({ has: page.getByRole('heading', { name: /^Заблоковано/ }) })
  await expect(blocked.getByRole('link', { name: 'Browser task', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/kanban-desktop.png', fullPage: true })
  await page.getByLabel('Статус: Browser task', { exact: true }).selectOption('DONE')
  await expect(page.locator('.kanban-column').filter({ has: page.getByRole('heading', { name: /^Виконано/ }) }).getByRole('link', { name: 'Browser task', exact: true })).toBeVisible()
  await page.goto(taskUrl)
  await expect(page.getByRole('combobox', { name: 'Статус задачі', exact: true })).toHaveValue('DONE')
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: 'Видалити', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Browser task', exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(projectUrl)
  await expect(page.getByRole('heading', { name: 'Browser project', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/project-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 768, height: 1024 })
  await page.goto('/rnd')
  await expect(page.getByRole('heading', { name: 'Дослідження та розробка' })).toBeVisible()
  const denied = await page.request.get('/api/users/options')
  expect(denied.status()).toBe(200)
  await page.getByRole('button', { name: /Вийти/ }).click()
  await expect(page.getByRole('heading', { name: 'Вхід до робочого простору' })).toBeVisible()
  expect((await page.request.get('/api/projects')).status()).toBe(401)
  await page.goto(taskUrl)
  await expect(page.getByRole('heading', { name: 'Вхід до робочого простору' })).toBeVisible()
})
