const codeLabels = {
  ACTIVE: 'Активний',
  INACTIVE: 'Неактивний',
  PLANNED: 'Заплановано',
  TODO: 'До виконання',
  IN_PROGRESS: 'У роботі',
  BLOCKED: 'Заблоковано',
  TESTING: 'Випробування',
  DONE: 'Виконано',
  COMPLETED: 'Завершено',
  FROZEN: 'Призупинено',
  OPEN: 'Відкрито',
  IN_REVIEW: 'На перевірці',
  APPROVED: 'Погоджено',
  REJECTED: 'Відхилено',
  CLOSED: 'Закрито',
  DEVELOPMENT: 'У розробці',
  READY: 'Готово',
  DEPRECATED: 'Застаріле',
  PRODUCTION: 'Виробництво',
  DRAFT: 'Чернетка',
  RELEASED: 'Затверджено',
  RETIRED: 'Виведено з використання',
  CONFIRMED: 'Підтверджено',
  MATERIALS: 'Забезпечення матеріалами',
  PARTIALLY_SHIPPED: 'Частково відвантажено',
  SHIPPED: 'Відвантажено',
  CANCELLED: 'Скасовано',
  PENDING_APPROVAL: 'Очікує погодження',
  REQUESTED: 'Запитано',
  WAITING: 'Очікує',
  PASSED: 'Пройдено',
  FAILED: 'Не пройдено',
  PASS: 'Успішно',
  FAIL: 'Невдало',
  PARTIAL: 'Частково',
  REQUIRED: 'Потрібно',
  RFQ: 'Запит ціни',
  ORDERED: 'Замовлено',
  PAID: 'Оплачено',
  IN_TRANSIT: 'У дорозі',
  CUSTOMS: 'На митниці',
  RECEIVED: 'Отримано',
  ISSUE: 'Проблема',
  LOW: 'Низький',
  NORMAL: 'Звичайний',
  HIGH: 'Високий',
  CRITICAL: 'Критичний',
  SERIAL: 'Серійний облік',
  BATCH: 'Партійний облік',
  QUANTITY: 'Кількісний облік',
  MOTOR_BENCH: 'Стендове випробування двигуна',
  ESC_BENCH: 'Стендове випробування регулятора',
  MOTOR: 'Двигун',
  ESC: 'Регулятор обертів',
  FLIGHT_CONTROLLER: 'Польотний контролер',
  BATTERY: 'Акумулятор',
  PROPELLER: 'Пропелер',
  CAMERA: 'Камера',
  VTX: 'Відеопередавач',
  RX: 'Приймач',
  GPS: 'GPS-модуль',
  FLIGHT: 'Льотне випробування',
  ENDURANCE: 'Випробування витривалості',
  RANGE: 'Випробування дальності',
  TEMPERATURE: 'Температурне випробування',
  FRAME: 'Рама',
  ANTENNA: 'Антена',
  POWER_MODULE: 'Модуль живлення',
  BASELINE: 'Базова',
  CANDIDATE: 'Кандидат',
  OTHER: 'Інше',
} as const

export function labelForCode(value: string) {
  return codeLabels[value as keyof typeof codeLabels] ?? value.replaceAll('_', ' ').toLocaleLowerCase('uk-UA')
}
